export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_ADMIN_REQUEST = "SIGNUP_ADMIN_REQUEST";
export const SIGNUP_ADMIN_SUCCESS = "SIGNUP_ADMIN_SUCCESS";
export const SIGNUP_ADMIN_FAILURE = "SIGNUP_ADMIN_FAILURE";